version: '2'
services:
  app:
    build: .
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
    ports:
      - "5000:5000"
  db:
    image: mysql
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
